language: go 
os: linux

services:
  - docker

branches:
  only:
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

jobs:
  include:
    - stage: build
      arch: amd64
      script:
        - |
          export TZ=Asia/Shanghai
          export IMAGE_NAME="bitleak/lmstfy"
          IMAGE_TAG="$TRAVIS_TAG-$TRAVIS_CPU_ARCH"
          echo building $IMAGE_NAME:$IMAGE_TAG
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker logout

    - arch: arm64 
      script:
        - |
          export TZ=Asia/Shanghai
          export IMAGE_NAME="bitleak/lmstfy"
          IMAGE_TAG="$TRAVIS_TAG-$TRAVIS_CPU_ARCH"
          echo building $IMAGE_NAME:$IMAGE_TAG
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker logout

    - stage: push
      script:
        - |
          export TZ=Asia/Shanghai
          export IMAGE_NAME="bitleak/lmstfy"
          IMAGE_TAG="$TRAVIS_TAG"
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          docker manifest create $IMAGE_NAME:$IMAGE_TAG --amend $IMAGE_NAME:$IMAGE_TAG-amd64 --amend $IMAGE_NAME:$IMAGE_TAG-arm64
          docker manifest inspect $IMAGE_NAME:$IMAGE_TAG
          docker manifest push $IMAGE_NAME:$IMAGE_TAG
          docker manifest create $IMAGE_NAME:latest --amend $IMAGE_NAME:$IMAGE_TAG-arm64 --amend $IMAGE_NAME:$IMAGE_TAG-arm64
          docker manifest inspect $IMAGE_NAME:latest
          docker manifest push $IMAGE_NAME:latest
          docker logout

